# Stage 1: Build the Angular app
FROM node:20.11.1-slim as build-stage

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --verbose

# Copy all files and build the application
COPY . .

RUN npm run build -- --configuration production

FROM nginx:alpine as production-stage

COPY --from=build-stage /app/dist/marketplace-web-client /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
