# Stage 1: Build the Angular app
FROM node:20.11.1-slim as build-stage

WORKDIR /app

COPY package*.json ./

RUN npm ci --no-progress --verbose

COPY . .

# Build the app in production mode
RUN npm run build -- --configuration production

FROM node:20.11.1-slim as production-stage

WORKDIR /app
RUN npm install -g serve


COPY --from=build-stage /app/dist/marketplace-web-client /app

EXPOSE 80

CMD ["serve", "-s", ".", "-l", "80"]
